### ISSUE TITLE
Clean UP & Dockerization eos481p

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos481p#1]

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
Start working on it.
Thanks.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @DhanshreeA 
I've open PR on the model and i did following changes in the model

(1) Delete all **.dvc** folder and files
(2) Modify **src/service.py** from predict to run api and changed `python {0}/grover/main.py {1} {2}` to `bash {0}/run.sh {0} {1} {2}`
(3) Move **main.py** from `grover folder` to `code folder`
(4) Add **run.sh** in framework
(5) Move` finetune folder` that contains model files to `checkpoints` and made necessary changes in **main.py**
(6) Move subfolders from `grover folder` to` code folder` so that **main.py** read the necessary packages successfully
(7) Did necessary changes in **main.py** to read python codes from `grover subfolders` successfully
(8) Edit Dockerfile, changed `conda install -c conda-forge rdkit=2021.03.4` to `pip install rdkit-pypi==2022.3.1b1`

Thanks

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
The PR is failing at` Model Test on PR / test (pull_request) ` and it is failing in `Ersilia Installation`. 

```
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed cleaning build dir for ersilia
```
```
Failed to build ersilia
ERROR: Could not build wheels for ersilia, which is required to install pyproject.toml-based projects
Error: Process completed with exit code 1.
```

You can view the full error log here https://github.com/ersilia-os/eos481p/actions/runs/5614808773/job/15213722621?pr=2

@Gemma, It is again due to AirTable or something else, kindly let me know

Thanks
